services:

  keelson-connector-camera-realsense-dev:
    build: .
    container_name: cam-realsense-dev
    restart: unless-stopped
    network_mode: "host"
    privileged: true
    command: "--log-level 10 -r rise -e purpose -s camera/0 --publish point_cloud --publish raw_color --publish raw_depth --frame_rate 6"
    
